name: Daily Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Hello, this is your daily task!"
