name: Daily Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Add Repository
        run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - name: Add Repository Key
        run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && sudo apt-get update
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client-16
      - name: Dump the PostgreSQL database
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          pg_dump -h ${{ secrets.POSTGRES_HOST }} \
                  -U ${{ secrets.POSTGRES_USER }} \
                  -d ${{ secrets.POSTGRES_DB }} \
                  -F c \
                  -b \
                  -v \
                  -f db_backup.dump
      - name: Upload dump to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: db_backup
          path: db_backup.dump