name: Daily Workflow

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Add Repository
        run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - name: Add Repository Key
        run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && sudo apt-get update
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client-16
      - name: Dump the PostgreSQL database
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          pg_dump -h ${{ secrets.POSTGRES_HOST }} \
                  -U ${{ secrets.POSTGRES_USER }} \
                  -d ${{ secrets.POSTGRES_DB }} \
                  -F c \
                  -b \
                  -v \
                  -f db_backup.dump
      - name: Upload dump to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: db_backup
          path: db_backup.dump
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli
      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}
      - name: Upload dump to S3
        run: aws s3 cp db_backup.dump s3://${{ secrets.S3_BUCKET }}/db_backup.dump --storage-class GLACIER_IR
      - name: Verify the dump
        run: aws s3 ls s3://${{ secrets.S3_BUCKET }}/db_backup.dump
        
